In [1]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale 
from sklearn import model_selection
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor

from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
from __future__ import division

In [3]:
import csv
MD = pd.read_csv('Milkdata.csv',sep=";")

In [4]:
MD.head()

No  Age   Sex      Occupation Likes Bananas Likes Chocolate  \
0   1   35  Male        Engineer           Yes             Yes   
1   2   36  Male         Teacher           Yes              No   
2   3   35  Male        Engineer            No              No   
3   4   39  Male  Medical Doctor            No             Yes   
4   5   37  Male    Truck Driver           Yes             Yes   

  Lactose Intolerant Likes Chocolate Banana Milkshake  Binary Sex  \
0                 No                              Yes           0   
1                 No                               No           0   
2                 No                               No           0   
3                Yes                               No           0   
4                Yes                              Yes           0   

   Binary Banana  Binary Chocolate  Binary Lactose  Binary Milkshake  
0              1                 1               0                 1  
1              1                 0               0                 0  
2              0                 0               0                 0  
3              0                 1               1                 0  
4              1                 1               1                 1

In [5]:
MD.drop(columns=['No', 'Age', 'Sex','Occupation', 'Likes Bananas', 'Likes Chocolate', 'Lactose Intolerant', 'Likes Chocolate Banana Milkshake'], inplace=True)

In [9]:
X = MD.drop(columns=['Binary Sex'])

In [10]:
Y=MD['Binary Sex']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.25, 
                                                    random_state=42)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
Kneighbor=KNeighborsClassifier()

In [21]:
Kneighbor.fit(X_train,y_train)

KNeighborsClassifier()

In [22]:
print(Kneighbor.predict(X_test))

[0 0 1 1 1 1 0 0 0]


In [28]:
y_pred = Kneighbor.predict(X_test)

In [29]:
print(y_pred)

[0 0 1 1 1 1 0 0 0]


Second Part-Label Encoding

In [31]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [32]:
import csv
LD = pd.read_csv('Milkdata.csv',sep=";")

In [33]:
LD_sex = LD['Sex']

In [34]:
LD_sex_encoded=le.fit_transform(LD_sex)
print(LD_sex_encoded)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
